import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Grid from "@mui/material/Grid";
import SidebarMenu from "./shared/sidebar/sidebar";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Grid container className="p-8 min-h-screen">
          <Grid item xs={2}>
            <SidebarMenu />
          </Grid>
          <Grid item xs={10}>
            {children}
          </Grid>
          <Toaster />
        </Grid>
      </body>
    </html>
  );
}
